
[pytest]
addopts = --html=reports/report.html --self-contained-html --maxfail=3
log_cli = true
log_cli_level = INFO
log_file = logs/test.log
log_file_level = INFO
testpaths = testCases
markers =
    smoke: quick tests to verify the core functionality
    regression: comprehensive tests for the entire application

[pytest.config]
env = test
